# Generated by Django 4.1.4 on 2022-12-12 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ligue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ligue', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_participant', models.CharField(max_length=50)),
                ('prenom_participant', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_match', models.CharField(max_length=50)),
                ('date_match', models.DateTimeField(verbose_name='Match date')),
                ('score_locaux', models.IntegerField(default=0)),
                ('score_visiteur', models.IntegerField(default=0)),
                ('ligue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligue', to='mesligues.ligue')),
                ('locaux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locaux', to='mesligues.participant')),
                ('visiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiteur', to='mesligues.participant')),
            ],
        ),
    ]
